# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'combobox_widget_for_COM.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import serial.tools.list_ports
import serial

s = serial.Serial(port="COM3", baudrate=9600)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setWindowTitle(QtCore.QCoreApplication.translate("Form", "Form"))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")

        self.createWidgetTitle("COM", Form)
        #DEVICE
        device = ["RaspberryPi", "Arduino", "Jetson Nano"]
        self.DeviceCombo = self.createComboBoxFrame("Device", device, Form)
        #PORT
        ports = serial.tools.list_ports.comports()
        port = []
        for p, desc, hwid in sorted(ports):
            port.append(p)
        self.PortCombo = self.createComboBoxFrame("Port", port, Form)
        #BAUDRATE
        baudrate = [300, 1200, 2400, 4800, 9600, 19200, 38400, 57600, 74880,
                    115200, 230400, 250000, 500000, 1000000, 2000000]
        baudrate = map(str, baudrate)
        self.BaudrateCombo = self.createComboBoxFrame("Baudrate", baudrate, Form)

        self.Connection = self.createConnectionFrame("Connect","Not Connected", Form)

        # QTIMER_FOR_COM_STATUS
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.showValueFromDevice)
        self.pushButton.clicked.connect(self.buttonPressed)

    def showValueFromDevice(self):
        if s.in_waiting > 0:
            res = s.readline().decode("Ascii")
            self.labelConnect.setText(res)
            self.labelConnect.setStyleSheet(
                "font: 63 8pt \"Lucida Sans\";\n"
                "color: rgb(85, 255, 0);"
            )
            print(res)

    def buttonPressed(self):
        if self.pushButton.text() == 'Connect':
            self.pushButton.setText('Disconnect')
            self.pushButton.setStyleSheet(
                "font: 63 8pt \"Lucida Sans\";\n"
                "color: rgb(255, 0, 0);"
            )
            self.timer.start(1000)

        else:
            self.pushButton.setText('Connect')
            self.labelConnect.setText('Not Connected')
            self.labelConnect.setStyleSheet(
                "font: 63 8pt \"Lucida Sans\";\n"
                "color: rgb(255, 0, 0);"
            )
            self.timer.stop()

    def createWidgetTitle(self, name, Form):
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setText(QtCore.QCoreApplication.translate("Form", name))
        self.label.setStyleSheet(
            "font: 63 12pt \"Lucida Sans\";\n"
            "color: rgb(170, 170, 255);"
        )
        self.verticalLayout.addWidget(self.label)

    def createComboBoxFrame(self, name, items, Form):
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setStyleSheet(
            "font: 63 10pt \"Lucida Sans\";\n"
            "color: rgb(170, 170, 255);"
        )
        self.label.setText(QtCore.QCoreApplication.translate("Form", name))
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.setStyleSheet(
            "font: 63 8pt \"Lucida Sans\";\n"
            "background-color: rgb(14, 152, 190);"
            "color: rgb(85, 255, 0);"
        )
        self.comboBox.addItems(items)
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.frame)

    def createConnectionFrame(self, name, status, Form):
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet(
            "font: 63 8pt \"Lucida Sans\";\n"
            "background-color: rgb(14, 152, 190);"
            "color: rgb(85, 255, 0);"
        )
        self.pushButton.setText(QtCore.QCoreApplication.translate("Form", name))
        self.horizontalLayout.addWidget(self.pushButton)
        self.labelConnect = QtWidgets.QLabel(self.frame)
        self.labelConnect.setAlignment(QtCore.Qt.AlignCenter)
        self.labelConnect.setObjectName("label")
        self.labelConnect.setStyleSheet(
            "font: 63 8pt \"Lucida Sans\";\n"
            "color: rgb(255, 0, 0);"
        )
        self.labelConnect.setText(QtCore.QCoreApplication.translate("Form", status))
        self.horizontalLayout.addWidget(self.labelConnect)
        self.verticalLayout.addWidget(self.frame)



# python -m PyQt5.uic.pyuic -x combobox_widget_for_COM.ui -o combobox_widget_for_COM.py


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
