# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frame_widget_for_CameraView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import cv2


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setWindowTitle(QtCore.QCoreApplication.translate("Form", "Form"))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")

        self.createWidgetTitle("Camera", Form)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.image_label = QtWidgets.QLabel(Form)
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.image_label.setText(QtCore.QCoreApplication.translate("Form", "Camera"))
        self.image_label.setStyleSheet(
            "font: 63 8pt \"Lucida Sans\";\n"
            "color: rgb(85, 255, 0);"
        )
        self.verticalLayout.addWidget(self.image_label)

        self.verticalLayout.addLayout(self.horizontalLayout)
        self.PushButton = self.createPushButton("Start", Form)
        # self.PushButton2 = self.createPushButton("Snap")

        # QTIMER_FOR_CAMERA
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.viewCam)
        self.pushButton.clicked.connect(self.buttonPressed)


    def viewCam(self):
        ret, image = self.cap.read()
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        height, width, channel = image.shape
        step = channel * width
        qImg = QtGui.QImage(image.data, width, height, step, QtGui.QImage.Format_RGB888)
        self.image_label.setPixmap(QtGui.QPixmap.fromImage(qImg))

    def buttonPressed(self):
        if self.pushButton.text() == 'Start':
            self.cap = cv2.VideoCapture(0)
            self.pushButton.setText('Stop')
            self.pushButton.setStyleSheet(
                "font: 63 8pt \"Lucida Sans\";\n"
                "background-color: rgb(14, 152, 190);"
                "color: rgb(255, 0, 0);"
            )
            self.timer.start(20)

        else:
            self.pushButton.setText('Start')
            self.pushButton.setStyleSheet(
                "font: 63 8pt \"Lucida Sans\";\n"
                "background-color: rgb(14, 152, 190);"
                "color: rgb(85, 255, 0);"
            )
            # self.labelConnect.setText('Not Connected')
            self.timer.stop()
            self.cap.release()
            self.image_label.setText('Camera')

    def createPushButton(self, name, Form):
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet(
            "font: 63 8pt \"Lucida Sans\";\n"
            "background-color: rgb(14, 152, 190);"
            "color: rgb(85, 255, 0);"
        )
        self.pushButton.setText(QtCore.QCoreApplication.translate("Form", name))
        self.horizontalLayout.addWidget(self.pushButton)

    def createWidgetTitle(self, name, Form):
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setText(QtCore.QCoreApplication.translate("Form", name))
        self.label.setStyleSheet(
            "font: 63 12pt \"Lucida Sans\";\n"
            "color: rgb(170, 170, 255);"
        )
        self.verticalLayout.addWidget(self.label)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())