# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import frame_for_CameraView
import combobox_for_COM
import mapwidget
import switch_widget
import sensor_status

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowTitle(QtCore.QCoreApplication.translate("MainWindow", "MainWindow"))
        MainWindow.resize(1400, 800)
        MainWindow.setStyleSheet("background-color: rgb(0, 56, 85);")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # self.centralwidget.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.horizontalLayout.addLayout(self.verticalLayout_1)

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        # self.widget = QtWidgets.QWidget(self.centralwidget)
        # self.widget.setObjectName("widget")
        # self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #Adding widgets

        #COM Widget
        self.com = QtWidgets.QWidget()
        self.COM = combobox_for_COM.Ui_Form()
        self.COM.setupUi(self.com)
        self.verticalLayout_1.addWidget(self.com)

        #Switch Widget
        self.switch = QtWidgets.QWidget()
        self.Switch = switch_widget.Ui_Form()
        self.Switch.setupUi(self.switch)
        self.verticalLayout_1.addWidget(self.switch)

        #Camera Widget
        self.cam = QtWidgets.QWidget()
        self.Camera = frame_for_CameraView.Ui_Form()
        self.Camera.setupUi(self.cam)
        self.verticalLayout_2.addWidget(self.cam)

        #Map Widget
        self.map = QtWidgets.QWidget()
        self.Map = mapwidget.Ui_Form()
        self.Map.setupUi(self.map)
        self.verticalLayout_2.addWidget(self.map)

        #Sensor Status Widget
        self.sensor = QtWidgets.QWidget()
        self.Sensor = sensor_status.Ui_Form()
        self.Sensor.setupUi(self.sensor)
        self.verticalLayout_3.addWidget(self.sensor)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
