# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frame_widget_for_MapLocation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import io
import folium
from PyQt5 import QtWidgets, QtWebEngineWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setWindowTitle(QtCore.QCoreApplication.translate("Form", "Form"))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")

        self.createWidgetTitle("Location",Form)
        self.viewMap()

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.PushButton = self.createPushButton("Sync Location", Form)

        # QTIMER_FOR_MAP
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.viewMap)
        self.pushButton.clicked.connect(self.buttonPressed)


    def viewMap(self):
        self.map = folium.Map(
            location=[23.780382, 90.407910], tiles="OpenStreetMap", zoom_start=13
        )

        folium.Marker(
            location=[23.780382, 90.407910],
            popup='Device',
        ).add_to(self.map)

        self.data = io.BytesIO()
        self.map.save(self.data, close_file=False)
        self.w = QtWebEngineWidgets.QWebEngineView()
        self.w.setHtml(self.data.getvalue().decode())

        self.verticalLayout.addWidget(self.w)

    def buttonPressed(self):
        self.w.setHtml(self.data.getvalue().decode())

    def createPushButton(self, name, Form):
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet(
            "font: 63 8pt \"Lucida Sans\";\n"
            "background-color: rgb(14, 152, 190);"
            "color: rgb(85, 255, 0);"
        )
        self.pushButton.setText(QtCore.QCoreApplication.translate("Form", name))
        self.horizontalLayout.addWidget(self.pushButton)

    def createWidgetTitle(self, name, Form):
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setText(QtCore.QCoreApplication.translate("Form", name))
        self.label.setStyleSheet(
            "font: 63 12pt \"Lucida Sans\";\n"
            "color: rgb(170, 170, 255);"
        )
        self.verticalLayout.addWidget(self.label)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
