# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_for_sensor_status.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setWindowTitle(QtCore.QCoreApplication.translate("Form", "Form"))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")

        self.createWidgetTitle("Sensor and Status", Form)

        self.depthStatus = self.createStatusFrame("Depth", Form)
        self.speedStatus = self.createStatusFrame("Speed", Form)
        self.pressureStatus = self.createStatusFrame("Pressure", Form)
        self.temperatureStatus = self.createStatusFrame("Temperature", Form)
        self.humidityStatus = self.createStatusFrame("Humidity", Form)


    def createWidgetTitle(self, name, Form):
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setText(QtCore.QCoreApplication.translate("Form", name))
        self.label.setStyleSheet(
            "font: 63 12pt \"Lucida Sans\";\n"
            "color: rgb(170, 170, 255);"
        )
        self.verticalLayout.addWidget(self.label)

    def createStatusFrame(self, name, Form):
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setStyleSheet(
            "font: 63 10pt \"Lucida Sans\";\n"
            "color: rgb(170, 170, 255);"
        )
        self.label.setText(QtCore.QCoreApplication.translate("Form", name))
        self.horizontalLayout.addWidget(self.label)
        self.statusLabel = QtWidgets.QLabel(self.frame)
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.statusLabel.setStyleSheet(
            "font: 63 8pt \"Lucida Sans\";\n"
            "background-color: rgb(14, 152, 190);"
            "color: rgb(85, 255, 0);"
        )
        self.statusLabel.setText(QtCore.QCoreApplication.translate("Form", "Unavailable"))
        self.horizontalLayout.addWidget(self.statusLabel)
        self.verticalLayout.addWidget(self.frame)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
